### ISSUE TITLE
Client_id and client_secret

### ISSUE THREAD

**Issue by ConstantinElias** [skroutz/developer.skroutz.gr#127]
Hello,

How can I obtain a valid client_id and client_secret in order to get access to resources of your API?

**Comment by spiroszermalias** [comment]
> Hello,
> 
> How can I obtain a valid client_id and client_secret in order to get access to resources of your API?

Did you happen to find out how? It should be mentioned right there in the documentation but it's not.

**Comment by kosdiamantis** [comment]
Hello,

I am really sorry for such a late response 😄 
We are no longer accept requests for new accesses regarding our API.
