### ISSUE TITLE
Webhook URL

### ISSUE THREAD

**Issue by ariskartalos** [skroutz/developer.skroutz.gr#138]
Καλημέρα, επειδή το eshop μας είναι στο domain πχ aaa.gr και θέλουμε το Webhook να φιλογξενείται σε άλλο domain πχ bbb.gr αυτό δεν το επιτρέπετε να δηλωθεί στο σύστημα. 
Ορίσαμε ένα subdomain πχ wh.aaa.gr να παραπέμπει στην IP του bbb.gr και το δηλώσαμε με επιτυχία στο Skroutz Webhook.
Δοκιμές simulation με Postman λειτουργούν. Δυστυχώς δεν δεχόμαστε κλήσεις από το Skroutz. 
Μήπως φταίει ότι αν και δηλώνουμε subdomain (wh.aaa.gr) το σύστημα προσπαθεί να στείλει στο aaa.gr αγνοώντας το subdomain? 
Μήπως φταίει κάποιος έλεγχος πιστοποιητικού ασφαλείας SSL?
Υπάρχει περίπτωση να μας επιτρέψετε την προώθηση κλήσεων σε άλλο domain?
Ευχαριστούμε εκ των προτέρων.

**Comment by nikostsaganos** [comment]
Καλημέρα!

Παρακαλώ στείλτε ένα νέο ticket μέσα από τo Merchants panel του συνεργάτη σας για να εξετάσουμε συγκεκριμένα τι μπορεί να συμβαίνει. 

Σε γενικές γραμμές, πρόκειται για curl requests με το flag `CURLOPT_SSL_VERIFYPEER`. Ένα ssl test εργαλείο που μπορεί να σας βοηθήσει είναι αυτό: https://www.ssllabs.com/ssltest 

Όσον αφορά τη χρήση του subdomain, είναι σωστή, ισχύει το "same domain policy" και επιτρέπονται subdomains. Στο ticket σας, συμπεριλάβετε και το διαφορετικό domain που έχετε εφόσον πρόκειται για domain του ίδιου καταστήματος για να ελέγξουμε αν μπορεί να χρησιμοποιηθεί. 

Ευχαριστούμε και καλές γιορτές!
Νίκος
