### ISSUE TITLE
Sizes documentation 

### ISSUE THREAD

**Issue by agelospanagiotakis** [skroutz/developer.skroutz.gr#141]
Βλέπουμε στο documentation την παρακάτω παράγραφο

Επίσης σε περίπτωση ρούχων τα μεγέθη μπορεί να έχουν ένα από τα παρακάτω format:

1) <size>XXS, XS, S, M, L, XL, XXL, XXXL</size>
2) <size>Extra Small, Small, Medium, Large, Extra Large</size>
3) <size>00, 0, 2, 4, 6, 8, 10, 12, 14, 16</size>

Ερώτηση
Αν αυτα ειναι 3 διαφορετικά φορματ 
το XXS πως γινεται στο δευτερο φορματ; 
το XXL πως γινεται στο δευτερο φορματ; 
το XXXL πως γινεται στο δευτερο φορματ;

**Comment by pharlez** [comment]
Hello @agelospanagiotakis!

The first two examples are not in fact mutually exclusive, but can be used in supplement to each other.
So for example, all examples below would be correctly recognised:
```
XXS, XS, S, M, L, XL, XXL, XXXL
XXS, XS, Small, Medium, Large, XL, XXL, XXXL
XXS, Extra Small, Small, Medium, Large, Extra Large, XXL, XXXL
```
