### ISSUE TITLE
Skroutz Analytics

### ISSUE THREAD

**Issue by Dimitra1213** [skroutz/developer.skroutz.gr#146]
My website is WordPress, I want to add the script in the thank you page to tracking orders and items and I can't understand for the example what part of the code I must to take and replace it. Example in the order_id:  '123456' with what I must to replace?

**Comment by harrisred** [comment]
Hi @Dimitra1213. For WordPress websites that use the WooCommerce ecommerce solution you can install the [Skroutz Analytics for WooCommerce plugin](https://wordpress.org/plugins/skroutz-analytics-woocommerce/). For any further questions regarding the Skroutz Analytics integration please send us an email at analytics@skroutz.gr.
