### ISSUE TITLE
XMLFeed// Shipping // τιμή 0 για δωρεάν μεταφορικά, δεν επιτρέπεται

### ISSUE THREAD

**Issue by Spoting** [skroutz/developer.skroutz.gr#157]
Καλησπέρα σας,

Θα χρειαστώ μία διευκρίνηση περί του πεδίου Shipping που θέλω να προσθέσω στο Skroutz Feed του πελάτη.

**Στο Skroutz Validator, μου λέει ότι απαγορεύεται η τιμή 0, ενώ το documentation λέει να βάλω την 0 αν θέλω να δείξω ότι ένα προιόν έχει δωρεάν μεταφορικά.** 
Μπορείτε να με κατευθύνεται ?

Επίσης, μία ακόμα ερώτηση αν είναι εφικτό. 
Μπορούμε να feedάρουμε πολλαπλά barcodes/eans ανά προιόν?

Ευχαριστώ πολύ για τον χρόνο σας.

**Comment by takhs91** [comment]
Καλησπέρα σας,
η τιμή 0 επιτρέπεται στο πεδίο shipping, απλά εμφανίζει warning προς αποφυγή λάθους (να βάλει δηλαδή κάποιος 0 σε όλα τα products κατα λάθος)

Αν δώσετε πολλαπλά comma separated EANs θα το δεχτεί (ean1, ean2..).

**Comment by Spoting** [comment]
Ευχαριστώ πολύ για την απάντηση!
