### ISSUE TITLE
skroutz script shopify

### ISSUE THREAD

**Issue by eirinibrek** [skroutz/developer.skroutz.gr#163]
Hello people. We are currently trying to make our online shop a member of an online shopping web-page platform  . To do so, we have to add some scripts to our page's codes. One of those, is a tracking script, that will send data (like the order id, product id, revenue etc)  after an order is completed. We are told that this script should be added to the thank you or checkout page. Since we do not have a Shopify plus submission, we are not allowed to access the checkout.liquid page, so we are trying to add it on settings/checkout/additional scripts but it is not sending them any data. Are we adding the code on the wrong place? Are there any mistakes on the script? Here you can see the code we are trying to add : 
<script>

  (function(a,b,c,d,e,f,g){a['SkroutzAnalyticsObject']=e;a[e]= a[e] || function(){
    (a[e].q = a[e].q || []).push(arguments);};f=b.createElement(c);f.async=true;
    f.src=d;g=b.getElementsByTagName(c)[0];g.parentNode.insertBefore(f,g);
  })(window,document,'script','https://analytics.skroutz.gr/analytics.min.js','skroutz_analytics');
  skroutz_analytics('session', 'connect', 'SA-XXXXX-066XX');  // Connect your Account.
</script>

<script>
  skroutz_analytics('ecommerce', 'addOrder',({
    order_id: '{{ order.name }}',   // Order ID. Required.
    revenue:  '{{ checkout.total_price | money}}',  // Grand Total. Includes Tax and Shipping. Does not include payment costs.
    shipping: '{{ shipping_method.price | money }}',     // Total Shipping Cost. Does not include payment costs.
    tax:      '{{ checkout.tax_price | money }}'    // Total Tax.
  }));
</script>

<script>
skroutz_analytics('ecommerce', 'addItem',({
order_id: '{{ order.name }}', 
product_id: {% for line in checkout.line_items %}
 {{ line.product.id }}
{% endfor %}, 
name: {% for line in checkout.line_items %} 
{{ line.product.title }}
{% endfor %} , 
price: {% for line in checkout.line_items %}
  {{ line.price   | money }}
{% endfor %}, 
quantity:  '{% for line in checkout.line_items %}}'
  '{{ line.quantity }}'
{% endfor %}

});

 
</script>

**Comment by mrwhizzy** [comment]
Hi @eirinibrek,

Unfortunately we do not provide technical support for the integration of Skroutz Analytics in Shopify shops.

However, the following links might be useful to you:
* https://shopify.dev/docs/liquid/reference/objects/order
* https://shopify.dev/docs/liquid/reference/objects/order#order-line_items
* https://shopify.dev/docs/liquid/reference/objects/for-loops
* https://shopify.dev/docs/liquid/reference/objects/line_item

We also recommend you to reach out to our support team, either via email to analytics@skroutz.gr or by using our ticketing system that can be found [here](https://merchants.skroutz.gr/merchants/help/new/services/skroutz_analytics).

We remain at your disposal for any clarification.
