### ISSUE TITLE
Unauthorized API Request

### ISSUE THREAD

**Issue by Parism** [skroutz/developer.skroutz.gr#166]
Καλησπέρα σας,

Πραγματοποιώ δοκιμές όσο αφορά στo Orders API σας αλλά ενώ χρησιμοποιώ ένα ενεργό API Token λαμβάνω συνεχώς ως απάντηση το μήνυμα με error code : EcommerceMerchantUnauthorized.

Μπορείτε να μας βοηθήσετε;

Ευχαριστώ.

**Comment by nikostsaganos** [comment]
Καλησπέρα σας, 

Παρακαλώ μπορείτε να στείλετε ένα ticket μέσα από το Merchants panel για μπορέσουμε να δούμε τι ακριβώς συμβαίνει;

Ευχαριστούμε πολύ!
