### ISSUE TITLE
Πως ακιρβώς παίρνουμε το client id και client-secret

### ISSUE THREAD

**Issue by Markos-Th09** [skroutz/developer.skroutz.gr#170]
Πως ακιρβώς παίρνουμε το client id και client-secret. Τα docs δεν λένε τίποτα για αυτό

**Comment by cioannid** [comment]
Γεια σου @Markos-Th09!

Το γενικό API προορίζεται πλέον μόνο για εσωτερική κατανάλωση και για αυτό δε μπορεί κάποιος εξωτερικός χρήστης να αποκτήσει client ID και client secret.

Τα APIs που διατίθενται για εξωτερική χρήση είναι το [Orders API](https://developer.skroutz.gr/smart_cart/orders_api/) και το [CPS Orders API](https://developer.skroutz.gr/cps_orders_api/). Και τα δύο αφορούν τη διασύνδεση των καταστημάτων με το Skroutz και απαιτούν ένα έγκυρο token. Αυτό μπορεί να εκδοθεί για κάθε κατάστημα μέσα από τη διαχειριστική σελίδα που τους παρέχεται από το Skroutz (Merchants Panel).

Καλή συνέχεια!
