### ISSUE TITLE
validator.skroutz.gr can no longer handle zip files

### ISSUE THREAD

**Issue by nickpapoutsis** [skroutz/developer.skroutz.gr#184]
Recently noticed that validator.skroutz.gr no longer accepts zip files as it stops with error `Line:1 Column:1 Start tag expected, '<' not found Please check the XML file with an XML validator`.

If I unzip the xml and test it on its own it works fine. If I gzip it it works fine too.

**Comment by MrGoumX** [comment]
Hello! The issue should be fixed. Validator can now process zip files once again! 

If there are any problems you can reopen this issue!
