### ISSUE TITLE
Allow API token access to Sandbox, not binded to a merchant

### ISSUE THREAD

**Issue by teokal** [skroutz/developer.skroutz.gr#203]
Hello,

we are currently working on implementing integration with Skroutz Marketplace, using Webhooks and Skroutz API.

At the moment, API token can only be issued from and for an active Skroutz merchant.

It would be nice, to have a generic developer/sandbox API token to access the DEMO-ORDERs, without depending on a customer.

Example:

```bash
curl -X GET https://api.skroutz.gr/merchants/ecommerce/orders/DEMO-OPEN \
  -H 'Accept: application/vnd.skroutz+json; version=3.0' \
  -H 'Authorization: Bearer skroutz-sandbox-api-token'
```

It would also allow us to write tests for our implementation without using a customer's API token.

I understand that triggering webhooks will not be possible, since it wouldn't know where to send an event. That would require creating a Developer account.

**Comment by cioannid** [comment]
Hello @teokal!

Thank you for your interest on Skroutz projects and your feedback. As you mentioned, API and Webhook are provided only to active merchants at the moment. We might consider your request based on the demand we have for it by all community members. Thank you.

Kind regards,
Skroutz Engineering
