### ISSUE TITLE
Allow updating voucher code using Skroutz API

### ISSUE THREAD

**Issue by teokal** [skroutz/developer.skroutz.gr#204]
Hello,

**Skroutz -> Eshop**

at the moment, there is support to receive the voucher code using the `order_updated` event type or using the `courier_tracking_codes` field when retrieving an order.

That only applies for accepted orders that Skroutz created a voucher.

**Eshop -> Skroutz**

When viewing a Skroutz Marketplace order, you have the option to enter a voucher code:

![image](https://user-images.githubusercontent.com/11727192/223720294-4f141c4b-6a3c-4327-99d3-bd53c49aad7d.png)

Would it be possible to allow updating this field using the Skroutz API?

**Comment by nikostsaganos** [comment]
Hello! Apologies for for missing this one! 

The flow you described, that allows a Merchant to submit their own tracking URL is accessible for specific Merchants only, in a "beta" phase. There is also an API endpoint for it in [Marketplace Orders API](https://developer.skroutz.gr/smart_cart/orders_api/) but is not publicly documented. If you need the documentation for this endpoint, please feel free to request it via a ticket in Merchants' panel, and we will get back at you shortly! 

Thank you!
