### ISSUE TITLE
Stock/Price batch update on Marketplace 

### ISSUE THREAD

**Issue by Bozionelos** [skroutz/developer.skroutz.gr#209]
Hi,

Is there any means of batch updating **only** stock/price/availability for products created within Marketplace?

**Comment by cioannid** [comment]
Hi @Bozionelos!

There is a way to update products information in bulk. This can happen by sending an XML file periodically. For details, you can refer to the [related document](https://developer.skroutz.gr/feedspec/).

If you need help for some specific shop, please open a ticket from its Merchants Panel, so we provide you targeted consultation.

Kind regards,
Skroutz Engineering
