### ISSUE TITLE
Validator issue

### ISSUE THREAD

**Issue by Lykos-Dim** [skroutz/developer.skroutz.gr#219]
Looks like validator is not working.
![image](https://github.com/skroutz/developer.skroutz.gr/assets/76428358/dd342ce6-696b-4ba6-ab1a-5eae92bdb6b5)

**Comment by argirisNt** [comment]
Hello @Lykos-Dim! Thanks for reaching out!
Could you give us more details about this?
In which step does this happen? What is your input?

**Comment by Lykos-Dim** [comment]
today it worked, so i think we can close this ticket

**Comment by argirisNt** [comment]
I'm glad it worked. If anything comes up again, don't hesitate to contact us.
