### ISSUE TITLE
Skroutz XML Feed - Shopify

### ISSUE THREAD

**Issue by xariskef** [skroutz/developer.skroutz.gr#220]
Καλησπέρα σας, 

Το app Skroutz XML Feed σε Shopify, δεν επιστρέφει στο xml feed additional images ενώ τα προιόντα έχουν περασμένες και αλλες φωτογραφίες. Αυτό είναι ένα app το οποίο το έχει φτιάξει η think-plus.gr. Εχω στείλει email για αυτο και δεν έχω πάρει απάντηση. Που πρέπει να αναφερθώ για αυτό; 

Με εκτίμηση.

**Comment by cioannid** [comment]
Καλημέρα @xariskef!

Ευχαριστούμε για το ενδιαφέρον σου στο Skroutz.

Το συγκεκριμένο Shopify app έχει υλοποιηθεί και συντηρείται από τρίτη εταιρεία και δε μπορούμε να παρέχουμε υποστήριξη για αυτό.

Ωστόσο, διαβάζοντας την περιγραφή και τις [κριτικές του app](https://apps.shopify.com/export-product-skroutz-xml-feed?surface_intra_position=1&surface_type=partners&surface_version=redesign#adp-reviews), φαίνεται ότι η λειτουργικότητα που αναζητείς είναι μέρος του premium πακέτου του app. Ενδεικτικά, υπάρχει μία κριτική από 24 Νοεμβρίου 2022 που μάλλον απαντά το ερώτημά σου.

Καλή συνέχεια,
Skroutz Engineering

**Comment by xariskef** [comment]
Ευχαριστώ πολυ για την απάντηση, 
Καλή σας μέρα.
