### ISSUE TITLE
Orders API - express delivery

### ISSUE THREAD

**Issue by OlgaLom** [skroutz/developer.skroutz.gr#229]
Καλησπέρα, εχουμε κάνει συνδεση της πλατφόρμας για να πεφτουν οι παραγγελίες και στο e-shop. Εχουμε ενεργοποιημένο το feature express delivery εδω και καιρό και οι παραγγελίες περνουσαν κανονικά. 

Σήμερα λάβαμε 2 express παραγγελίες οπού έγιναν  accepted με status "προς αποστολή" αλλά δεν πέρασαν την σελίδα. 
Η απαντηση απο το curl command για την αποδοχη της παραγγελίας είναι η παρακάτω. Η διαδικασία ολοκληρώθηκε δηλαδη απο open εγινε eccepted αλλα η απαντηση ηταν error. Μπορείτε να μου πείτε λίγο παραπάνω για αυτό το error διότι δεν βρήκα κατι σχετικό στο documentation. 

```
[errors] => Array
        (
            [0] => Array
                (
                    [code] => order_status
                    [messages] => Array
                        (
                            [0] => Order is express
                        )

                )

        )
```

**Comment by mzachariadis** [comment]
Καλησπέρα @OlgaLom, 

Πρόσφατα έγινε μια αλλαγή όπου για μια παραγγελία Express δεν επιτρέπουμε την αποδοχή μέσω του API, διότι οι παραγγελίες Express γίνονται αυτόματα αποδεκτές από το Skroutz. Επομένως το status της παραγγελίας άλλαξε σε `accepted` λόγω της αυτόματης αποδοχής και όχι λόγω της κλήσης προς στο API. 

[Ενημερώσαμε και το documentation](https://developer.skroutz.gr/smart_cart/orders_api/#accept-a-single-order). 

Κλείνω το issue και ό,τι άλλο χρειαστεί μας ενημερώνεις. 

Καλή συνέχεια!
