### ISSUE TITLE
woocommerce σε shopify

### ISSUE THREAD

**Issue by aigencydev** [skroutz/developer.skroutz.gr#232]
Άλλαξα το κατάστημα μου από woocommerce σε shopify και δεν μπορω να βρω κάποια λύση πως να στειλω την παραγγελια μιας και το shopify δεν σου επιτρεπει να επεμβεις στην σελιδα checkout ή thank you. Μπορείτε να με βοήθησετε μιας και έχετε plugin μονο για woocommerce

**Comment by mrwhizzy** [comment]
Καλησπέρα σας από το Skroutz,

Για το συγκεκριμένο ζήτημα θα παρακαλούσαμε να επικοινωνήσετε μαζί μας μέσω ticket από το χώρο συνεργατών.

Εναλλακτικά, μπορείτε να στείλετε ένα mail στο [analytics@skroutz.gr](mailto:analytics@skroutz.gr).

Με εκτίμηση
