### ISSUE TITLE
VAT Exclusion Representative - List of possible ID Type values

### ISSUE THREAD

**Issue by teokal** [skroutz/developer.skroutz.gr#236]
Hello,

we recently added support for Invoice 39a orders and we want to extend this feature for the Skroutz Marketplace orders using Skroutz API.

We have the following questions:

1. Do you perform an eligibility check (using AADE's vt39afpaBu3GetBuyer) if the buyer is entitled to VAT exclusion?

2. Can you add the id_type ID to the API response?

```json
      "vat_exclusion_representative": {
        "id_type_id": 1,
        "id_type": "ΑΤ Αστυνομική Ταυτότητα",
        "id_number": "12345",
        "otp": "123456"
      }
```

```json
      "vat_exclusion_representative": {
        "id_type_id": 8,
        "id_type": "Διαβατήριο",
        "id_number": "12345",
        "otp": "123456"
      }
```

3. If (2) is not possible, can you publish a list with all the possible values of field `invoice_details.vat_exclusion_representative.id_type`? 

Issue here is that the API returned values, do not match with AADE's documentation. As such, we will have to create a mapping on our side.

**Examples**

| ID | AADE | Skroutz |
| ----- | ----- | ----- |
| 1 | ΑΤ ΑΣΤΥΝΟΜΙΚΗ ΤΑΥΤΟΤΗΤΑ | ΑΤ Αστυνομική Ταυτότητα |
| 8 | ΔΙ ΔΙΑΒΑΤΗΡΙΟ | Διαβατήριο |

**Related Documentation**

* **AADE**: Chapter 10.6.4 - https://www.aade.gr/dl_assets/39afpa/developer_guide_aade39afpaV1.3.pdf

* **Skroutz Developer** - https://developer.skroutz.gr/smart_cart/orders_api/#vat-exclusion-representative

**Comment by fotistsisk** [comment]
Dear @teokal,

Thank you for reaching out and providing valuable feedback.

1. Yes, the system does perform an eligibility check using AADE's vt39afpaBu3GetBuyer to determine if the buyer is entitled to VAT exclusion. This is done as part of the order processing workflow.

2. Unfortunately, it's not possible to add the id_type ID to the API response from our system.

3. We understand the importance of having a comprehensive list of possible values for the field invoice_details.vat_exclusion_representative.id_type. We will take your suggestion into account and work towards updating our documentation to include this information. This will help developers like you to have a better understanding of the possible values and their corresponding meanings.

We appreciate your patience and understanding in this matter. Your feedback is instrumental in helping us improve our services.  

Best Regards, Tsiskakis Fotis
