### ISSUE TITLE
VAT rate in order API

### ISSUE THREAD

**Issue by marianperca** [skroutz/developer.skroutz.gr#241]
Hi! Is it possible to include the VAT rate in the order response? Specifically in the line item object.  
We have multiple VAT rates and having the product VAT rate included would help a lot.
For example:
```
"line_items": [
      {
        "id": "l39vKqxqwe",
        "shop_uid": "100",
        "product_name": "Smartphone 123",
        "quantity": 2,
        "unit_price": 100,
        "total_price": 200,
        "vat_rate": "19",
         ...
      },
```

**Comment by fotistsisk** [comment]
Hello @marianperca,

Thank you for your valuable feedback regarding the inclusion of the VAT rate in the line item object. We understand how having the VAT rate directly in the order response could simplify things for you, especially with multiple VAT rates involved.

We appreciate your suggestion and will definitely look into it as we work to improve our system. Your input helps us provide a better experience, and we're always open to suggestions.

Thanks again, and feel free to reach out if you have any more ideas or questions!

Best regards,
Tsiskakis Fotis
