### ISSUE TITLE
API for ordering as a customer

### ISSUE THREAD

**Issue by midriasi** [skroutz/developer.skroutz.gr#243]
Hello! I’m exploring ways to automate Skroutz & Skroutz Supermarket orders and would like to know if there’s an API available for placing orders programmatically. I’m interested in using LLMs to track past orders and automatically generate new orders based on historical data. If not available, is this something you consider adding it in the future? Thank you.

**Comment by fotistsisk** [comment]
Hello @midriasi,

At the moment, we do not offer an API for placing orders programmatically, and it's not currently on our development roadmap. However, we always appreciate feedback and suggestions from our users, as they help us consider future enhancements.

We'll certainly keep your suggestion in mind as we continue to develop our services. If you have any other ideas or questions, please feel free to share them with us.

Best regards,

Tsiskakis Fotis
