### ISSUE TITLE
EAN code not received by webhook

### ISSUE THREAD

**Issue by esslava** [skroutz/developer.skroutz.gr#244]
Hello,

In our integration with Skroutz API, we have a webhook which receives notifications from Skroutz. There was a case in which our customer was not notified correctly through webhook, due to a missing EAN code from the received message. However, the product have EAN code assigned to it. Please check the following image.

![image](https://github.com/user-attachments/assets/8a213dba-79ae-4ecf-a43b-48b9daf94e2d)
The left side shows the message received by webhook.

Why could that happen? Under which conditions the EAN code is not received?

Thank you in advance

**Comment by fotistsisk** [comment]
Hello @esslava,

Considering that this matter involves customer data, I would kindly recommend that you communicate with us via [merchants panel](https://merchants.skroutz.gr/) to ensure proper handling and security.

Best regards,
Tsiskakis Fotis
