### ISSUE TITLE
Conditional Requests seem to not be working

### ISSUE THREAD

**Issue by pligor** [skroutz/developer.skroutz.gr#75]
The example from the developer API documentation does not seem to be working even if you change the dates: http://developer.skroutz.gr/api/v3/#conditional-requests

Trying different kinds of requests like getting specifications of an SKU or retrieving the first page of the review of an SKU none seems to contain the Last-Modified response header and thus the conditional request is not working. In all cases, the response code is 200, even if the "If-Modified-Since" header points a time and date in the future.

See a screenshot from Postman (chrome app) here:
![image](https://cloud.githubusercontent.com/assets/1448173/26450295/ad217d4a-414e-11e7-8037-3c776f6ad372.png)

How could this be fixed?

**Comment by freestyl3r** [comment]
You are correct. The `Last-Modified` header is no longer returned.
Updated the documentation to reflect the current state.

Thanks for reporting it!

**Comment by pligor** [comment]
Hi freestyl3r and thanks for the swift reply.

Looking at the updated documentation it seems that there is no way someone could avoid being charged for any kind of request.

So if you want to do a simple request like "get the latest reviews for all mobile phones" then this could be very costly. You need to retrieve all the pages for all skus of mobile phones which could approximately be 700 skus x 5 pages of reviews on average (rough estimation) ~= 3500 requests ! <-- this is way above the limit I have been given.

Any work around or solution for this? Thank you

**Comment by freestyl3r** [comment]
Hello again.

Like we mentioned in the API request approval email, we do not support mass extraction of data (product prices etc), from our backend systems.

The API is mainly provided for educational purposes.

Thanks for contacting us.
