### ISSUE TITLE
Analytics Implementation Issue

### ISSUE THREAD

**Issue by ctampak** [skroutz/developer.skroutz.gr#86]
I am trying to implement the analytics API, while the tracking script is integrated merchants/analytics/integrators/ reports missing tracking script.

I did some research and I can see all the iframes correctly generated and I get no errors from the console and from the Network tab I see all script down to easyXDM to load correctly.

Any ideas are welcome

**Comment by harrisred** [comment]
Hi @ctampak. Please open a ticket in [Skroutz Merchants](https://merchants.skroutz.gr/merchants/help), as we need to know which shop you are trying to integrate with Skroutz Analytics. 
Thank you.
