### ISSUE TITLE
 Open-Cart  Skroutz problem 

### ISSUE THREAD

**Issue by dimitris110985** [skroutz/developer.skroutz.gr#95]
Hello we have an E-shop made by open cart and have issues in validating ( sizes,titles,avalaibility ) i have taken the task to fix them so we can procceed by importing our website to skroutz store but i have problems fixing those issues . Any help is welcomed thank you.

**Comment by kosdiamantis** [comment]
Hello @dimitris110985 ,

For any issue you have, you can contact the Account Manager who is responsible for your E-shop through the shop's application form or by sending a new ticket from https://merchants.skroutz.gr.

If you are experiencing issues with your XML's structure you can also use our XML validator: https://validator.skroutz.gr

Thank you.
